import { ReactNode, useRef } from 'react';
import { Download, Printer, RefreshCw } from 'lucide-react';
import { useCompanySettings } from '../../contexts/CompanySettingsContext';
import { resolveApiBase } from '../../lib/apiBase';

interface Props {
  title: string;
  subtitle?: string;
  loading?: boolean;
  onRefresh?: () => void;
  onExportCsv?: () => void;
  filters?: ReactNode;
  children: ReactNode;
  printTitle?: string;
}

export default function ReportShell({
  title, subtitle, loading, onRefresh, onExportCsv, filters, children, printTitle,
}: Props) {
  const contentRef = useRef<HTMLDivElement>(null);
  const { settings: companySettings } = useCompanySettings();
  const apiBase = resolveApiBase();
  const logoSrc = companySettings.logo_url
    ? companySettings.logo_url.startsWith('http') ? companySettings.logo_url : `${apiBase}${companySettings.logo_url}`
    : null;
  const showLogo = companySettings.show_logo_in_reports && !!logoSrc;
  const showHeader = companySettings.show_company_header_in_reports;
  const companyName = companySettings.company_name || 'My Business';

  function handlePrint() {
    const content = contentRef.current;
    if (!content) return;
    const win = window.open('', '_blank', 'width=900,height=700');
    if (!win) return;
    const headerHtml = showHeader ? `
      ${showLogo ? `<div style="text-align:center;margin-bottom:6px;"><img src="${logoSrc}" alt="Logo" style="max-height:50px;object-fit:contain;" /></div>` : ''}
      <div style="text-align:center;margin-bottom:2px;">
        <strong style="font-size:14px;">${companyName}</strong>
      </div>
      ${companySettings.company_address ? `<div style="text-align:center;font-size:11px;color:#555;">${companySettings.company_address}</div>` : ''}
      ${companySettings.contact_number ? `<div style="text-align:center;font-size:11px;color:#555;">${companySettings.contact_number}</div>` : ''}
      <hr style="margin:8px 0;" />
    ` : '';
    const footerHtml = companySettings.footer_notes
      ? companySettings.footer_notes
      : `Generated by ${companyName}`;
    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${printTitle ?? title}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, sans-serif; font-size: 11px; padding: 24px; color: #111; }
          h1 { font-size: 16px; font-weight: bold; margin-bottom: 2px; }
          h2 { font-size: 12px; color: #555; margin-bottom: 16px; font-weight: normal; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f1f5f9; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; padding: 6px 8px; border-bottom: 2px solid #cbd5e1; text-align: left; }
          td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
          tr:nth-child(even) td { background: #f8fafc; }
          .text-right { text-align: right; }
          .font-mono { font-family: 'Courier New', monospace; }
          .badge { display: inline-block; padding: 1px 6px; border-radius: 9999px; font-size: 9px; font-weight: 600; }
          .badge-ok { background: #dcfce7; color: #166534; }
          .badge-low { background: #fef9c3; color: #854d0e; }
          .badge-out { background: #fee2e2; color: #991b1b; }
          .badge-critical { background: #fee2e2; color: #991b1b; }
          .badge-near { background: #fef9c3; color: #854d0e; }
          .badge-expired { background: #fce7f3; color: #9d174d; }
          .footer { margin-top: 20px; font-size: 9px; color: #94a3b8; text-align: right; }
          @media print { body { padding: 12px; } }
        </style>
      </head>
      <body>
        ${headerHtml}
        <h1>${printTitle ?? title}</h1>
        <h2>${subtitle ?? ''} &nbsp; Printed: ${new Date().toLocaleString('en-PH')}</h2>
        ${content.innerHTML}
        <div class="footer">${footerHtml} &bull; ${new Date().toLocaleDateString('en-PH')}</div>
      </body>
      </html>
    `);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); win.close(); }, 400);
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="px-6 py-4 flex items-center justify-between gap-4">
          <div>
            <h1 className="text-lg font-bold text-slate-800">{title}</h1>
            {subtitle && <p className="text-sm text-slate-500 mt-0.5">{subtitle}</p>}
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            {onRefresh && (
              <button
                onClick={onRefresh}
                disabled={loading}
                className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors disabled:opacity-50"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
                Refresh
              </button>
            )}
            {onExportCsv && (
              <button
                onClick={onExportCsv}
                className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                CSV
              </button>
            )}
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium text-white bg-slate-700 hover:bg-slate-800 rounded-lg transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
          </div>
        </div>

        {filters && (
          <div className="px-6 pb-3 flex items-center gap-3 flex-wrap border-t border-slate-100 pt-3">
            {filters}
          </div>
        )}
      </div>

      {/* Content */}
      <div className="p-6">
        {loading ? (
          <div className="flex items-center justify-center py-24">
            <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <div ref={contentRef}>
            {children}
          </div>
        )}
      </div>
    </div>
  );
}
