/*
  # Purchase Orders Module

  ## Summary
  Adds a full purchase order system to the inventory module.
  Supports multi-line POs per supplier and location, with automatic
  total computation and received quantity tracking.

  ## New Tables

  ### purchase_orders
  - Header record per PO: supplier, location, dates, status, totals
  - po_number is auto-generated (PO-YYYYMMDD-NNNN sequence per day)
  - Statuses: draft, approved, partially_received, fully_received, closed, cancelled

  ### purchase_order_items
  - One row per product line on a PO
  - Tracks ordered qty, received qty, unit cost, and line total
  - received_qty is updated when goods are received (future receiving module)

  ## Computed Columns (via trigger)
  - purchase_orders.subtotal = sum of (qty_ordered * unit_cost) per line
  - purchase_orders.total_amount = subtotal + tax_amount + other_charges - discount_amount
  - Status auto-advances to partially_received / fully_received when received qty changes

  ## Security
  - RLS enabled on both tables
  - Authenticated users can read
  - Admins can insert / update / delete

  ## Notes
  - po_number is unique and generated by a before-insert trigger
  - Cancelling a PO only allowed from draft or approved status
  - Closing is a manual admin action after fully received
*/

-- -----------------------------------------------
-- PO status enum
-- -----------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'po_status') THEN
    CREATE TYPE po_status AS ENUM (
      'draft',
      'approved',
      'partially_received',
      'fully_received',
      'closed',
      'cancelled'
    );
  END IF;
END $$;

-- -----------------------------------------------
-- purchase_orders
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_number text UNIQUE NOT NULL DEFAULT '',
  supplier_id uuid NOT NULL REFERENCES inv_suppliers(id) ON DELETE RESTRICT,
  location_id uuid NOT NULL REFERENCES inv_locations(id) ON DELETE RESTRICT,
  status po_status NOT NULL DEFAULT 'draft',
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_date date,
  approved_date date,
  approved_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  notes text NOT NULL DEFAULT '',
  terms text NOT NULL DEFAULT '',
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  discount_amount numeric(14,2) NOT NULL DEFAULT 0,
  other_charges numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS idx_po_location ON purchase_orders(location_id);
CREATE INDEX IF NOT EXISTS idx_po_status ON purchase_orders(status);
CREATE INDEX IF NOT EXISTS idx_po_order_date ON purchase_orders(order_date DESC);
CREATE INDEX IF NOT EXISTS idx_po_number ON purchase_orders(po_number);

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read purchase_orders"
  ON purchase_orders FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can insert purchase_orders"
  ON purchase_orders FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Admins can update purchase_orders"
  ON purchase_orders FOR UPDATE
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Admins can delete purchase_orders"
  ON purchase_orders FOR DELETE
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

-- -----------------------------------------------
-- purchase_order_items
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES inv_products(id) ON DELETE RESTRICT,
  qty_ordered numeric(12,3) NOT NULL DEFAULT 0,
  qty_received numeric(12,3) NOT NULL DEFAULT 0,
  unit_cost numeric(12,2) NOT NULL DEFAULT 0,
  line_total numeric(14,2) GENERATED ALWAYS AS (qty_ordered * unit_cost) STORED,
  notes text NOT NULL DEFAULT '',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_poi_po ON purchase_order_items(po_id);
CREATE INDEX IF NOT EXISTS idx_poi_product ON purchase_order_items(product_id);

ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read purchase_order_items"
  ON purchase_order_items FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can insert purchase_order_items"
  ON purchase_order_items FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Admins can update purchase_order_items"
  ON purchase_order_items FOR UPDATE
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Admins can delete purchase_order_items"
  ON purchase_order_items FOR DELETE
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

-- -----------------------------------------------
-- Function: generate_po_number
-- Generates PO-YYYYMMDD-NNNN format
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION generate_po_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  today_str text;
  seq_num   int;
  new_po_number text;
BEGIN
  today_str := to_char(CURRENT_DATE, 'YYYYMMDD');

  SELECT COUNT(*) + 1
    INTO seq_num
    FROM purchase_orders
   WHERE po_number LIKE 'PO-' || today_str || '-%';

  new_po_number := 'PO-' || today_str || '-' || LPAD(seq_num::text, 4, '0');
  NEW.po_number := new_po_number;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_generate_po_number ON purchase_orders;
CREATE TRIGGER trg_generate_po_number
  BEFORE INSERT ON purchase_orders
  FOR EACH ROW
  WHEN (NEW.po_number = '')
  EXECUTE FUNCTION generate_po_number();

-- -----------------------------------------------
-- Function: sync_po_totals
-- Recalculates subtotal and total_amount on the PO
-- whenever items are inserted/updated/deleted
-- Also auto-updates PO status based on received qty
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION sync_po_totals()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_po_id uuid;
  v_subtotal numeric(14,2);
  v_total numeric(14,2);
  v_total_ordered numeric(12,3);
  v_total_received numeric(12,3);
  v_new_status po_status;
  v_current_status po_status;
BEGIN
  -- Determine which PO to update
  IF TG_OP = 'DELETE' THEN
    v_po_id := OLD.po_id;
  ELSE
    v_po_id := NEW.po_id;
  END IF;

  -- Sum line totals
  SELECT
    COALESCE(SUM(qty_ordered * unit_cost), 0),
    COALESCE(SUM(qty_ordered), 0),
    COALESCE(SUM(qty_received), 0)
  INTO v_subtotal, v_total_ordered, v_total_received
  FROM purchase_order_items
  WHERE po_id = v_po_id;

  -- Get current header values for charges
  SELECT
    status,
    v_subtotal + tax_amount + other_charges - discount_amount
  INTO v_current_status, v_total
  FROM purchase_orders
  WHERE id = v_po_id;

  -- Determine new status (only auto-advance for approved+)
  IF v_current_status IN ('approved', 'partially_received', 'fully_received') THEN
    IF v_total_received = 0 THEN
      v_new_status := 'approved';
    ELSIF v_total_received >= v_total_ordered THEN
      v_new_status := 'fully_received';
    ELSE
      v_new_status := 'partially_received';
    END IF;
  ELSE
    v_new_status := v_current_status;
  END IF;

  UPDATE purchase_orders
     SET subtotal     = v_subtotal,
         total_amount = v_subtotal + tax_amount + other_charges - discount_amount,
         status       = v_new_status,
         updated_at   = now()
   WHERE id = v_po_id;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_po_totals ON purchase_order_items;
CREATE TRIGGER trg_sync_po_totals
  AFTER INSERT OR UPDATE OR DELETE ON purchase_order_items
  FOR EACH ROW
  EXECUTE FUNCTION sync_po_totals();
